import { CssVar, cssVarRef, FontStack, Palette, Section, Selector, ShikiVar } from "./constants";
import type { ControlDef, Schema } from "./types";

export const SCHEMA_VERSION = 1;

const tableBorderRef = cssVarRef(CssVar.tableBorder);
const tableStripeRef = cssVarRef(CssVar.tableStripe);

interface HeadingDefaults {
  fontSize: number;
  color: string;
  marginTop: number;
  marginBottom: number;
}

function headingControls(
  selector: string,
  label: string,
  defaults: HeadingDefaults,
): Record<string, ControlDef> {
  const prefix = label.toLowerCase();
  return {
    [`${prefix}.fontSize`]: {
      type: "dimension",
      emitter: "prop",
      control: "slider",
      default: defaults.fontSize,
      min: 10,
      max: 60,
      step: 1,
      unit: "pt",
      allowedUnits: ["pt", "px"],
      css: { selector, prop: "font-size" },
      section: Section.headings,
      label: `${label} size`,
    },
    [`${prefix}.fontWeight`]: {
      type: "fontWeight",
      emitter: "prop",
      control: "slider",
      default: 700,
      min: 100,
      max: 900,
      step: 100,
      css: { selector, prop: "font-weight" },
      section: Section.headings,
      label: `${label} weight`,
    },
    [`${prefix}.color`]: {
      type: "color",
      emitter: "prop",
      control: "color",
      default: defaults.color,
      format: "hex",
      css: { selector, prop: "color" },
      section: Section.headings,
      label: `${label} color`,
    },
    [`${prefix}.marginTop`]: {
      type: "dimension",
      emitter: "prop",
      control: "slider",
      default: defaults.marginTop,
      min: 0,
      max: 60,
      step: 1,
      unit: "pt",
      css: { selector, prop: "margin-top" },
      section: Section.headings,
      label: `${label} space above`,
    },
    [`${prefix}.marginBottom`]: {
      type: "dimension",
      emitter: "prop",
      control: "slider",
      default: defaults.marginBottom,
      min: 0,
      max: 40,
      step: 1,
      unit: "pt",
      css: { selector, prop: "margin-bottom" },
      section: Section.headings,
      label: `${label} space below`,
    },
  };
}

const controls: Record<string, ControlDef> = {
  // Page
  "page.size": {
    type: "enum",
    emitter: "page",
    control: "select",
    default: "A4",
    enum: ["A4", "Letter", "Legal"],
    css: { atPage: "size" },
    section: Section.page,
    label: "Page size",
  },
  "page.marginTop": {
    type: "dimension",
    emitter: "page",
    control: "slider",
    default: 20,
    min: 0,
    max: 50,
    step: 1,
    unit: "mm",
    css: { atPage: "margin-top" },
    section: Section.page,
    label: "Margin top",
  },
  "page.marginRight": {
    type: "dimension",
    emitter: "page",
    control: "slider",
    default: 18,
    min: 0,
    max: 50,
    step: 1,
    unit: "mm",
    css: { atPage: "margin-right" },
    section: Section.page,
    label: "Margin right",
  },
  "page.marginBottom": {
    type: "dimension",
    emitter: "page",
    control: "slider",
    default: 20,
    min: 0,
    max: 50,
    step: 1,
    unit: "mm",
    css: { atPage: "margin-bottom" },
    section: Section.page,
    label: "Margin bottom",
  },
  "page.marginLeft": {
    type: "dimension",
    emitter: "page",
    control: "slider",
    default: 18,
    min: 0,
    max: 50,
    step: 1,
    unit: "mm",
    css: { atPage: "margin-left" },
    section: Section.page,
    label: "Margin left",
  },
  "page.background": {
    type: "color",
    emitter: "prop",
    control: "color",
    default: Palette.white,
    format: "hex",
    css: { selector: Selector.root, prop: "background-color" },
    section: Section.page,
    label: "Background",
  },

  // Body
  "body.fontFamily": {
    type: "fontFamily",
    emitter: "prop",
    control: "select",
    default: FontStack.sans,
    css: { selector: Selector.root, prop: "font-family" },
    section: Section.body,
    label: "Font family",
    synonyms: ["text font", "typeface"],
  },
  "body.fontSize": {
    type: "dimension",
    emitter: "prop",
    control: "slider",
    default: 11,
    min: 8,
    max: 18,
    step: 0.5,
    unit: "pt",
    allowedUnits: ["pt", "px"],
    css: { selector: Selector.root, prop: "font-size" },
    section: Section.body,
    label: "Font size",
  },
  "body.color": {
    type: "color",
    emitter: "prop",
    control: "color",
    default: Palette.ink,
    format: "hex",
    css: { selector: Selector.root, prop: "color" },
    section: Section.body,
    label: "Text color",
  },
  "body.lineHeight": {
    type: "number",
    emitter: "prop",
    control: "slider",
    default: 1.6,
    min: 1,
    max: 2.4,
    step: 0.05,
    css: { selector: Selector.root, prop: "line-height" },
    section: Section.body,
    label: "Line height",
  },

  // Headings
  ...headingControls(Selector.heading1, "H1", {
    fontSize: 28,
    color: Palette.inkStrong,
    marginTop: 24,
    marginBottom: 12,
  }),
  ...headingControls(Selector.heading2, "H2", {
    fontSize: 22,
    color: Palette.inkStrong,
    marginTop: 20,
    marginBottom: 10,
  }),
  ...headingControls(Selector.heading3, "H3", {
    fontSize: 17,
    color: Palette.inkStrong,
    marginTop: 16,
    marginBottom: 8,
  }),

  // Links
  "link.color": {
    type: "color",
    emitter: "prop",
    control: "color",
    default: Palette.link,
    format: "hex",
    css: { selector: Selector.link, prop: "color" },
    section: Section.links,
    label: "Link color",
  },
  "link.textDecoration": {
    type: "enum",
    emitter: "prop",
    control: "select",
    default: "underline",
    enum: ["none", "underline"],
    css: { selector: Selector.link, prop: "text-decoration" },
    section: Section.links,
    label: "Decoration",
  },
  "link.fontWeight": {
    type: "fontWeight",
    emitter: "prop",
    control: "slider",
    default: 400,
    min: 100,
    max: 900,
    step: 100,
    css: { selector: Selector.link, prop: "font-weight" },
    section: Section.links,
    label: "Weight",
  },

  // Inline code
  "codeInline.fontFamily": {
    type: "fontFamily",
    emitter: "prop",
    control: "select",
    default: FontStack.mono,
    css: { selector: Selector.codeInline, prop: "font-family" },
    section: Section.codeInline,
    label: "Font family",
  },
  "codeInline.fontSize": {
    type: "dimension",
    emitter: "prop",
    control: "slider",
    default: 0.9,
    min: 0.6,
    max: 1.2,
    step: 0.05,
    unit: "em",
    css: { selector: Selector.codeInline, prop: "font-size" },
    section: Section.codeInline,
    label: "Font size",
  },
  "codeInline.color": {
    type: "color",
    emitter: "prop",
    control: "color",
    default: Palette.danger,
    format: "hex",
    css: { selector: Selector.codeInline, prop: "color" },
    section: Section.codeInline,
    label: "Text color",
  },
  "codeInline.background": {
    type: "color",
    emitter: "prop",
    control: "color",
    default: Palette.surface,
    format: "hex",
    css: { selector: Selector.codeInline, prop: "background-color" },
    section: Section.codeInline,
    label: "Background",
  },

  // Code block
  "codeBlock.fontSize": {
    type: "dimension",
    emitter: "prop",
    control: "slider",
    default: 10,
    min: 7,
    max: 16,
    step: 0.5,
    unit: "pt",
    css: { selector: Selector.codeBlock, prop: "font-size" },
    section: Section.codeBlock,
    label: "Font size",
  },
  // Shiki sets `background-color: var(--shiki-background)` inline on the <pre>, which beats any class
  // rule, so the block background is controlled through that variable instead of a prop.
  "codeBlock.background": {
    type: "color",
    emitter: "cssVar",
    control: "color",
    default: Palette.codeSurface,
    format: "hex",
    css: { var: ShikiVar.background },
    section: Section.codeBlock,
    label: "Background",
  },
  "codeBlock.padding": {
    type: "dimension",
    emitter: "prop",
    control: "slider",
    default: 14,
    min: 0,
    max: 40,
    step: 1,
    unit: "px",
    css: { selector: Selector.codeBlock, prop: "padding" },
    section: Section.codeBlock,
    label: "Padding",
  },
  "codeBlock.borderRadius": {
    type: "dimension",
    emitter: "prop",
    control: "slider",
    default: 8,
    min: 0,
    max: 24,
    step: 1,
    unit: "px",
    css: { selector: Selector.codeBlock, prop: "border-radius" },
    section: Section.codeBlock,
    label: "Corner radius",
  },
  "codeBlock.lineHeight": {
    type: "number",
    emitter: "prop",
    control: "slider",
    default: 1.5,
    min: 1,
    max: 2.2,
    step: 0.05,
    css: { selector: Selector.codeBlock, prop: "line-height" },
    section: Section.codeBlock,
    label: "Line height",
  },
  "codeBlock.wrap": {
    type: "boolean",
    emitter: "boolean",
    control: "toggle",
    default: false,
    css: {
      whenTrue: `${Selector.codeBlockText} { white-space: pre-wrap; word-break: break-word; }`,
    },
    section: Section.codeBlock,
    label: "Wrap long lines",
  },

  // Syntax colors (Shiki css-variables theme)
  "syntax.foreground": {
    type: "color",
    emitter: "cssVar",
    control: "color",
    default: Palette.syntaxForeground,
    format: "hex",
    css: { var: ShikiVar.foreground },
    section: Section.codeColors,
    label: "Foreground",
  },
  "syntax.comment": {
    type: "color",
    emitter: "cssVar",
    control: "color",
    default: Palette.textFaint,
    format: "hex",
    css: { var: ShikiVar.tokenComment },
    section: Section.codeColors,
    label: "Comment",
  },
  "syntax.keyword": {
    type: "color",
    emitter: "cssVar",
    control: "color",
    default: Palette.syntaxKeyword,
    format: "hex",
    css: { var: ShikiVar.tokenKeyword },
    section: Section.codeColors,
    label: "Keyword",
  },
  "syntax.string": {
    type: "color",
    emitter: "cssVar",
    control: "color",
    default: Palette.syntaxString,
    format: "hex",
    css: { var: ShikiVar.tokenString },
    section: Section.codeColors,
    label: "String",
  },
  "syntax.number": {
    type: "color",
    emitter: "cssVar",
    control: "color",
    default: Palette.syntaxNumber,
    format: "hex",
    css: { var: ShikiVar.tokenConstant },
    section: Section.codeColors,
    label: "Number / constant",
  },
  "syntax.function": {
    type: "color",
    emitter: "cssVar",
    control: "color",
    default: Palette.syntaxFunction,
    format: "hex",
    css: { var: ShikiVar.tokenFunction },
    section: Section.codeColors,
    label: "Function",
  },

  // Tables
  "table.headerBg": {
    type: "color",
    emitter: "prop",
    control: "color",
    default: Palette.surface,
    format: "hex",
    css: { selector: Selector.tableHeaderCell, prop: "background-color" },
    section: Section.tables,
    label: "Header background",
  },
  "table.headerColor": {
    type: "color",
    emitter: "prop",
    control: "color",
    default: Palette.inkStrong,
    format: "hex",
    css: { selector: Selector.tableHeaderCell, prop: "color" },
    section: Section.tables,
    label: "Header text",
  },
  "table.borderColor": {
    type: "color",
    emitter: "cssVar",
    control: "color",
    default: Palette.border,
    format: "hex",
    css: { var: CssVar.tableBorder },
    section: Section.tables,
    label: "Border color",
  },
  "table.borderMode": {
    type: "enum",
    emitter: "multiRule",
    control: "select",
    default: "horizontal",
    enum: ["all", "horizontal", "none"],
    rules: {
      all: [{ selector: Selector.tableAnyCell, decl: `border: 1px solid ${tableBorderRef}` }],
      horizontal: [
        { selector: Selector.tableRow, decl: `border-bottom: 1px solid ${tableBorderRef}` },
      ],
      none: [],
    },
    section: Section.tables,
    label: "Borders",
  },
  "table.cellPaddingX": {
    type: "dimension",
    emitter: "prop",
    control: "slider",
    default: 10,
    min: 0,
    max: 32,
    step: 1,
    unit: "px",
    css: { selector: Selector.tableAnyCell, prop: "padding-inline" },
    section: Section.tables,
    label: "Cell padding X",
  },
  "table.cellPaddingY": {
    type: "dimension",
    emitter: "prop",
    control: "slider",
    default: 6,
    min: 0,
    max: 32,
    step: 1,
    unit: "px",
    css: { selector: Selector.tableAnyCell, prop: "padding-block" },
    section: Section.tables,
    label: "Cell padding Y",
  },
  "table.stripe": {
    type: "boolean",
    emitter: "boolean",
    control: "toggle",
    default: false,
    css: { whenTrue: `${Selector.tableStripeRow} { background: ${tableStripeRef}; }` },
    section: Section.tables,
    label: "Zebra striping",
  },
  "table.stripeColor": {
    type: "color",
    emitter: "cssVar",
    control: "color",
    default: Palette.surfaceFaint,
    format: "hex",
    css: { var: CssVar.tableStripe },
    section: Section.tables,
    label: "Stripe color",
  },

  // Blockquote
  "blockquote.borderLeftWidth": {
    type: "dimension",
    emitter: "prop",
    control: "slider",
    default: 4,
    min: 0,
    max: 12,
    step: 1,
    unit: "px",
    css: { selector: Selector.blockquote, prop: "border-left-width" },
    section: Section.blockquote,
    label: "Bar width",
  },
  "blockquote.borderLeftColor": {
    type: "color",
    emitter: "prop",
    control: "color",
    default: Palette.border,
    format: "hex",
    css: { selector: Selector.blockquote, prop: "border-left-color" },
    section: Section.blockquote,
    label: "Bar color",
  },
  "blockquote.color": {
    type: "color",
    emitter: "prop",
    control: "color",
    default: Palette.textMuted,
    format: "hex",
    css: { selector: Selector.blockquote, prop: "color" },
    section: Section.blockquote,
    label: "Text color",
  },
  "blockquote.fontStyle": {
    type: "enum",
    emitter: "prop",
    control: "select",
    default: "italic",
    enum: ["normal", "italic"],
    css: { selector: Selector.blockquote, prop: "font-style" },
    section: Section.blockquote,
    label: "Style",
  },
  "blockquote.paddingLeft": {
    type: "dimension",
    emitter: "prop",
    control: "slider",
    default: 16,
    min: 0,
    max: 48,
    step: 1,
    unit: "px",
    css: { selector: Selector.blockquote, prop: "padding-left" },
    section: Section.blockquote,
    label: "Indent",
  },
};

export const schema: Schema = {
  version: SCHEMA_VERSION,
  controls,
};
