// Reads the bundled woff2 files and regenerates packages/core/src/fonts.ts with the @font-face layer
// as base64 data URLs. Run after changing any file under fonts/. The output is committed (pinned) so
// the build never depends on the binaries at runtime; embedding makes the exported PDF self-contained
// and lets the preview iframe (no fetch origin) and headless Chromium resolve the same faces.

import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(HERE, "..");
const FONTS_DIR = resolve(REPO_ROOT, "fonts");
const OUTPUT = resolve(REPO_ROOT, "packages/core/src/fonts.ts");

// The family name must equal the first token of the matching FontStack entry in constants.ts so the
// generated rules and the user-selectable stacks resolve to the same face.
/** @type {{ family: string; style: "normal" | "italic"; weight: number; file: string }[]} */
const FACES = [
  { family: "Inter", style: "normal", weight: 400, file: "inter/Inter-Regular.woff2" },
  { family: "Inter", style: "italic", weight: 400, file: "inter/Inter-Italic.woff2" },
  { family: "Inter", style: "normal", weight: 600, file: "inter/Inter-SemiBold.woff2" },
  { family: "Inter", style: "normal", weight: 700, file: "inter/Inter-Bold.woff2" },
  {
    family: "JetBrains Mono",
    style: "normal",
    weight: 400,
    file: "jetbrains-mono/JetBrainsMono-Regular.woff2",
  },
  {
    family: "JetBrains Mono",
    style: "italic",
    weight: 400,
    file: "jetbrains-mono/JetBrainsMono-Italic.woff2",
  },
  {
    family: "JetBrains Mono",
    style: "normal",
    weight: 700,
    file: "jetbrains-mono/JetBrainsMono-Bold.woff2",
  },
];

async function buildFace(face) {
  const bytes = await readFile(resolve(FONTS_DIR, face.file));
  const dataUrl = `data:font/woff2;base64,${bytes.toString("base64")}`;
  return (
    `@font-face{font-family:'${face.family}';font-style:${face.style};font-weight:${face.weight};` +
    `font-display:swap;src:url(${dataUrl}) format('woff2')}`
  );
}

const rules = await Promise.all(FACES.map(buildFace));

const file = `${[
  "// GENERATED by scripts/embed-fonts.mjs — do not edit by hand. Regenerate after changing fonts/.",
  "// Base64-embedded woff2 @font-face rules for the bundled families (Inter, JetBrains Mono). Kept out",
  "// of generateCss so the golden CSS snapshot stays font-free; prepended like BASE_CSS by both the",
  "// preview pipeline and the PDF document so preview and export resolve identical faces.",
  "",
].join("\n")}export const FONT_FACE_CSS = ${JSON.stringify(rules.join("\n"))};\n`;

await writeFile(OUTPUT, file);
process.stdout.write(`Wrote ${OUTPUT} (${rules.length} faces)\n`);
